CREATE TABLE Agency.ContactInfo
(
	ContactID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	BillingAddress NVARCHAR(200) NOT NULL,
	Phone NVARCHAR(30) NOT NULL,
	Email NVARCHAR(120) NOT NULL,
	CityID INT NOT NULL,
	FOREIGN KEY
	(
		CityID
	)
	REFERENCES [Location].Cities(CityID),	

)