CREATE TABLE Hotels.Hotel 
(
    HotelID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    [Name] NVARCHAR(120) NOT NULL,
    CityID INT NOT NULL FOREIGN KEY REFERENCES [Location].Cities(CityID),
    FullAddress NVARCHAR(120) NOT NULL
);